### ISSUE TITLE
waypoint_updater. usage of closest_waypoint probable issue

### ISSUE THREAD

**Issue by buffos** [kung-fu-panda-automotive/carla-driver#20]
I think using as is closest waypoint function, does not make it clear if the waypoint is in front or behind us.
If it's **behind** us, we have a problem with the current code, because we include it again in the list of waypoints.

**Comment by mithi** [comment]
@buffos @ljanyst, @mauricelos, @asimonov how do you think we should go about this?

Do you think we should implement a function like this like the one given at the path planning project?
`lines 64 to 83` of https://github.com/udacity/CarND-Path-Planning-Project/blob/master/src/main.cpp

```
int NextWaypoint(double x, double y, double theta, vector<double> maps_x, vector<double> maps_y){

    int closestWaypoint = ClosestWaypoint(x,y,maps_x,maps_y);

    double map_x        = maps_x[closestWaypoint];
    double map_y        = maps_y[closestWaypoint];
    double heading      = atan2((map_y-y), (map_x-x));
    double angle        = abs(theta-heading);

    if (angle > pi()/4) {
        closestWaypoint++;
    }

    return closestWaypoint;
}

```

**Comment by buffos** [comment]
I think yes. It is much more logical to pick the closest point **in front** of us,

**Comment by buffos** [comment]
May I ask If this is actually necessary at all? closest or nearest?

Are we given generally waypoints, or **only** the points in front of us?

Did you check if the index found is never more than 0?

I mean I did not read anywhere that the waypoints are out of order so

* either we do not need closest and/or nearest at all
* or we need nearest

**Comment by buffos** [comment]
No need to look further into that
