### ISSUE TITLE
waypoint_updater: calculate target angular velocities

### ISSUE THREAD

**Issue by buffos** [kung-fu-panda-automotive/carla-driver#23]
Except setting the target linear velocities per waypoint, we also need to set the angular velocities.
A way to do it is the following

a)  fit a polynomial path of degree 2 to the waypoints in front of us. for example (treat as meta code)
``` python
    x_coords = [waypoint.pose.pose.position.x for waypoint in waypoints]
    y_coords = [waypoint.pose.pose.position.y for waypoint in waypoints]
    return np.polyfit(x_coords, y_coords, degree)
```
b) create a function that will calculate the radius of the curve, as in the advance lane identification project. It should calculate it x,y => Radius(x,y) . Sample code from that lessons, for a degree=2 polynomial

``` python
    def calculateRCurve(coefficients, X):
        if coefficients is None:
            return None
        a = coefficients[0]
        b = coefficients[1]
        return (1 + (2 * a * X + b) ** 2) ** 1.5 / np.absolute(2 * a)
```

for higher degrees use the formula [here](https://wikimedia.org/api/rest_v1/media/math/render/svg/8c371c3a26f78a89d42d5a8b9b5e8a55d53600b8)

c) for every waypoint, set the angular velocity from the formula  R = linear velocity/angular velocity
For small values of R, set angular velocity to zero.  so

` angular_velocity[waypoint] = linear_velocity[waypoint]/Radius[waypoint]`

**Comment by mauricelos** [comment]
How do I determine what degree the polynomial should have?

**Comment by mithi** [comment]
@mauricelos  Maybe we just try degree 2, or 3 and see which is best?

**Comment by asimonov** [comment]
Trying to reply on email... 

I think degree 2 or 3 is the best.

_____________________________
Kind Regards,
Alexey Simonov

**Comment by mauricelos** [comment]
Okay, I will try both, thanks!

**Comment by mauricelos** [comment]
Dumb question, but what is X in the calculateRCurve function?

**Comment by mauricelos** [comment]
X = f(y) ???

**Comment by buffos** [comment]
Yes, since you fit xs and ys... you get a polynomial f(Y)

**Comment by buffos** [comment]
Better try just degree 2 (as we did in that project) that we are sure of the formula of Radius curvature.

**Comment by mauricelos** [comment]
Wait, it's just the x values from the waypoints right?!

**Comment by buffos** [comment]
Yes... for each x... you get a p(x)= y. 
(x,y) is the waypoint
R(x,y) is the radius


do NOT use 1-degree polynomial. That is a straight line... You will not get any turning angles along path

**Comment by buffos** [comment]
in the beginning, we just have (x,y) from waypoints
we fit them to get a curve np.polyfit(xs,ys)
then create the R(x,y) function that gives us the radius for x,y
so for each waypoint now (x,y) we have the linear velocity (constant for now) and R(x,y), so we get the angular velocity by dividing
